import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo日記",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="font-sans">
        <div className="mx-auto w-[400px]">{children}</div>
      </body>
    </html>
  );
}
